// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FilterController from "./filter_controller";
application.register("filter", FilterController);

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller";
application.register("modal", ModalController);

import NavBarController from "./nav_bar_controller";
application.register("nav-bar", NavBarController);

import ZipCodeController from "./zip_code_controller";
application.register("zip-code", ZipCodeController);
