require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.4
  NewCops: enable
  Exclude:
    - '.git/**/*'
    - '.idea/**/*'
    - 'Rakefile'
    - 'bin/**/*'
    - 'config/initializers/devise.rb'
    - 'db/**/*'
    - 'init/*'
    - 'scratch*.rb'
    - 'snippets*.rb'
    - 'vendor/**/*'
RSpec/NestedGroups:
  Max: 4
